# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="maniek"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras svn sudo vi-mode autojump cp extract pip lol nyan screen)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
#

HOSTNAME=$(hostname)
if [[ "$HOSTNAME" -eq "lynx" ]]
then
    export HOST_PROMPT_COLOR='green'
elif [[ "$HOSTNAME" -eq "mariusz-desktop" ]]
then
    export HOST_PROMPT_COLOR='yellow'
else
    export HOST_PROMPT_COLOR='white'
fi

export VIRTUAL_ENV_DISABLE_PROMPT=1
source ~/.zsh/zshrc_global
source ~/.utils/utils.rc
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh

export PATH=/home/$USER/bin:$PATH
#export PATH=$PATH:/usr/bin/site_perl/
#export PYTHONPATH="/home/maniek/programing/django/lib/python2.6/site-packages"
export PYTHONIOENCODING='utf-8'

export MPD_HOST="127.0.0.1"
export MPD_PORT="6600"

export CVSROOT=":pserver:maniek@rshare.pl:/home/cvs/"

alias halt='sudo halt'
alias reboot='sudo reboot'
alias E='gvim --remote-tab'

function VENV
{
    [[ -z $1 ]] && echo "No virtualenv specified" && exit 1
    source ~/"virtualenv/$1/bin/activate"
}

alias E='gvim --servername "$(basename $([[ -n $VIRTUAL_ENV ]] && echo $VIRTUAL_ENV || echo GVIM))" --remote-tab'

